server.port=8080
spring.application.name=smartgpay

# Disable Spring Cloud GCP AlloyDB and Cloud SQL Auto-Configurations (for local PostgreSQL)
spring.cloud.gcp.alloydb.enabled=false
spring.cloud.gcp.sql.enabled=false

# Disable Spring Cloud GCP BigQuery Auto-Configuration (custom BigQueryConfig bean is used)
spring.cloud.gcp.bigquery.enabled=false

# Spring Cloud GCP Credentials Location
spring.cloud.gcp.credentials.location=file:src/main/resources/gcp-key.json

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/smartgpay
spring.datasource.username=postgres
spring.datasource.password=javeriya@2002
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# GCP & Gemini Configuration
gcp.project-id=smartgpay
gcp.location=us-central1
gcp.credentials-path=src/main/resources/gcp-key.json

# Google Cloud BigQuery Configuration
spring.cloud.gcp.bigquery.project-id=smartgpay
spring.cloud.gcp.bigquery.dataset-name=smartgpay_analytics
gcp.bigquery.credentials.path=src/main/resources/gcp-key.json